export const userColumns = [
  { field: "id", headerName: "No", width: 60 },
  {
    field: "nama",
    headerName: "Nama",
    width: 250,
    renderCell: ( params ) =>
    {
      return params.row.username;
    },
  },
  {
    field: "email",
    headerName: "Email",
    width: 250,
  },
  {
    field: "role",
    headerName: "Role",
    width: 200,
  },
  {
    field: "productivity",
    headerName: "Productivity",
    width: 130,
  },
  {
    field: "contribution",
    headerName: "Contribution",
    width: 130,
  },
];

//temporary data
export const userRows = [
  {
    id: "1",
    username: "Jhon",
    role: "Design",
    email: "jhon@gmail.com",
    productivity: "90%",
    contribution: "80%",
  },
  {
    id: "2",
    username: "Kim",
    role: "Frontend",
    email: "kim@gmail.com",
    productivity: "70%",
    contribution: "90%",
  },
  {
    id: "3",
    username: "David",
    role: "Backend",
    email: "david@gmail.com",
    productivity: "10%",
    contribution: "30%",
  },
  {
    id: "4",
    username: "Jane",
    role: "Mobile",
    email: "jane@gmail.com",
    productivity: "95%",
    contribution: "90%",
  },
  {
    id: "5",
    username: "Dave",
    role: "Quality Analist",
    email: "dave@gmail.com",
    productivity: "50%",
    contribution: "60%",
  },
  {
    id: "6",
    username: "Alex",
    role: "Analyst",
    email: "alex@gmail.com",
    productivity: "70%",
    contribution: "80%",
  },
  {
    id: "7",
    username: "Ucup",
    role: "Project Manager",
    email: "ucup@gmail.com",
    productivity: "80%",
    contribution: "90%",
  },
  {
    id: "8",
    username: "Asep",
    role: "Design",
    email: "asep@gmail.com",
    productivity: "62%",
    contribution: "70%",
  },
  {
    id: "9",
    username: "Gunawan",
    role: "Mobile",
    email: "gunawan@gmail.com",
    productivity: "10%",
    contribution: "20%",
  },
  {
    id: "10",
    username: "Diana",
    role: "Analyst",
    email: "diana@gmail.com",
    productivity: "20%",
    contribution: "30%",
  },
  {
    id: "11",
    username: "Agus",
    role: "Frontend",
    email: "agus@gmail.com",
    productivity: "80%",
    contribution: "90%",
  },
  {
    id: "12",
    username: "Smith",
    role: "Quality Analyst",
    email: "smith@gmail.com",
    productivity: "90%",
    contribution: "100%",
  },
  {
    id: "13",
    username: "Marsel",
    role: "Analyst",
    email: "marsel@gmail.com",
    productivity: "60%",
    contribution: "70%",
  },
  {
    id: "14",
    username: "Putri",
    role: "Admin",
    email: "putri@gmail.com",
    productivity: "55%",
    contribution: "65%",
  },
  {
    id: "15",
    username: "Jesica",
    role: "Admin",
    email: "jesica@gmail.com",
    productivity: "75%",
    contribution: "85%",
  },
  {
    id: "16",
    username: "Dulla",
    role: "Project Manager",
    email: "dulla@gmail.com",
    productivity: "53%",
    contribution: "63%",
  },

];
